version: 0.2

env:
  variables:
    IMAGE_NAME: "aws-code-build"

phases:
  install:
    commands:
      - echo "🚀 Installing dependencies..."
      - yum update -y
      - yum install -y docker

  pre_build:
    commands:
      - echo "🔑 Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "📂 Checking if required files exist in the workspace..."
      - ls -la  # Debugging step to verify all files are present
      - |
        MISSING_FILES=0
        for file in "awslogo.png" "style.css" "script.js" "index.html"; do
          if [ ! -f "$file" ]; then 
            echo "❌ ERROR: $file is missing!"
            MISSING_FILES=1
          fi
        done
        if [ $MISSING_FILES -eq 1 ]; then 
          exit 1
        fi
      - echo "✅ All required files are present!"
      - echo "🏗️  Building the Docker image..."
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

  post_build:
    commands:
      - echo "📤 Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
      - echo "🎉 Build completed successfully!"

artifacts:
  files:
    - index.html
    - style.css
    - script.js
    - awslogo.png  # ✅ Ensures AWS CodeBuild pulls this file
    - Dockerfile
    - buildspec.yml
